### ISSUE TITLE
Can't get any images, only black squares

### ISSUE THREAD

**Issue by ArmPub** [dkxce/MapnikTileRenderer#1]
Hi!
Could you provide any examples (mapnik xml and datasources), that can be rendered.
I have tried to render shape files and osm files and got only black squares instead of images.
What the reason for that might be?
Here is xml example i used

<?xml version="1.0" encoding="utf-8" ?> 
<Map srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
  
    <Layer name="world" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
        <Datasource>
            <Parameter name="file">world_merc.shp</Parameter>
            <Parameter name="encoding">iso-8859-1</Parameter>
            <Parameter name="type">shape</Parameter>
        </Datasource>
    </Layer>

</Map>

**Comment by dkxce** [comment]
You should set full path to target shape file whitout extention.
Samples are in `samples_maps_*`.

```
<Layer name="HOUSE_POINTS_uz" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ">
	<StyleName>HOUSE_POINTS</StyleName>
	<Datasource>
            <Parameter name="file">D:\__Mapnik\MyTown\HOUSE_uz</Parameter>	
            <Parameter name="row_limit">0</Parameter>
            <Parameter name="type">shape</Parameter>
            <Parameter name="encoding">windows-1251</Parameter>
        </Datasource>
    </Layer>
```

Sample in [Release](https://github.com/dkxce/MapnikTileRenderer/releases/tag/MapnikTileRenderer_v21.10.07.0): `IRKUTSK_SAMPLE.zip `
