### ISSUE TITLE
postgis plugin can't be registered

### ISSUE THREAD

**Issue by ArmPub** [dkxce/MapnikTileRenderer#2]
Hi!
There is a postgis plugin mapnik_postgis.input, but it doesn't read by MapnikCs.DatasourceCache.RegisterDatasources command.
Others plugins are succesfully registered, but this one doesn't.

I run a code like this

MapnikCs.DatasourceCache.RegisterDatasources(cd + @"data_sources\");
MapnikCs.StringsList sl = MapnikCs.DatasourceCache.PluginNames;

and there is no postgis plugin in stringslist...

**Comment by dkxce** [comment]
Unfortunately I was unable to launch this plugin. There might be an error in it somewhere.
